# 1. What is a Python library? Why do we use Python libraries?

# 2. What is the difference between Numpy array an^ List?

# 3. Fin^ the shape, size an^ ^imension of the following array?

In [1]:
import numpy as np

In [4]:
arr=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])

In [5]:
np.shape(arr)

(3, 4)

In [6]:
np.size(arr)

12

In [13]:
arr.shape

(3, 4)

In [8]:
arr.size

12

In [10]:
np.ndim(arr)

2

In [11]:
arr.ndim

2

# 4. Write python co^e to access the first row of the following array?

In [19]:
arr=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
element=arr[0,:]
print(element)

[1 2 3 4]


# 5. How ^o you access the element at the thir^ row an^ fourth column from the given numpy array?

In [21]:
arr=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
print(arr[:,2])
print(arr[:,3])

[ 3  7 11]
[ 4  8 12]


# 6. Write co^e to extract all o^^-in^exe^ elements from the given numpy array?

In [29]:
arr=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
print(arr[1::2,1::2])

[[6 8]]


# 7.How can you generate a ran^om 3x3 matrix with values between 0 an^ 1?

In [39]:
arr=np.random.rand(3,3)
print(arr)

[[0.98298749 0.28974713 0.46889665]
 [0.91773745 0.62194839 0.95587722]
 [0.56982017 0.04461298 0.45103229]]


# 8. Describe the ^ifference between np.ran^om.ran^ an^ np.ran^om.ran^n?

# 9. Write co^e to increase the ^imension of the following array?

In [40]:
arr=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
arr.ndim

2

In [41]:
np.expand_dims(arr,axis=0)

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]]])

In [42]:
np.expand_dims(arr,axis=1)

array([[[ 1,  2,  3,  4]],

       [[ 5,  6,  7,  8]],

       [[ 9, 10, 11, 12]]])

# 10. How to transpose the following array in NumPy?

In [44]:
arr=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
print(np.transpose(arr))
print(arr.T)

[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]
[[ 1  5  9]
 [ 2  6 10]
 [ 3  7 11]
 [ 4  8 12]]


In [45]:
a=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])
b=np.array([[1, 2, 3, 4],
            [5, 6, 7, 8],
            [9, 10, 11, 12]])

In [46]:
a*b

array([[  1,   4,   9,  16],
       [ 25,  36,  49,  64],
       [ 81, 100, 121, 144]])

In [52]:
a.T@b

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

In [53]:
a@b.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [54]:
b.T@a

array([[107, 122, 137, 152],
       [122, 140, 158, 176],
       [137, 158, 179, 200],
       [152, 176, 200, 224]])

In [55]:
b@a.T

array([[ 30,  70, 110],
       [ 70, 174, 278],
       [110, 278, 446]])

In [49]:
a+b

array([[ 2,  4,  6,  8],
       [10, 12, 14, 16],
       [18, 20, 22, 24]])

In [50]:
b-a

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [51]:
b/a

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

# 12. Which function in Numpy can be use^ to swap the byte or^er of an array?

# 13. What is the significance of the np.linalg.inv function?

# 14. What ^oes the np.reshape function ^o, an^ how is it use^?

# 15. What is broa^casting in Numpy?